#!/bin/sh
cd `dirname $0`
. /etc/hifiberry.state

if [ ! -f /etc/spotifyd.conf ]; then
  cp spotifyd.conf.default /etc/spotifyd.conf
fi

grep "/etc/spotifyd.conf" /etc/config-files
if [ "$?" != "0" ]; then
  echo "/etc/spotifyd.conf">>/etc/config-files
fi

if [ ! -f /etc/dbus-1/system.d/spotifyd.conf ]; then

cat <<EOF>/etc/dbus-1/system.d/spotifyd.conf
<!DOCTYPE busconfig PUBLIC "-//freedesktop//DTD D-BUS Bus Configuration 1.0//EN"
 "http://www.freedesktop.org/standards/dbus/1.0/busconfig.dtd">
<busconfig>

 <!-- Root can own the Spotify service -->
  <policy user="player">
    <allow own="org.mpris.MediaPlayer2.spotifyd"/>
  </policy>

</busconfig>
EOF
systemctl restart dbus

fi
